source : /home/$USER/Pictures/Files/Camera/
destination : /home/$USER/Pictures/Files2/
compression_type : 7z
uplink_path_destination : memories20220919/
uplink_path_type : sj://
log_file : log.txt
parallel_upload : 5
parallel_upload_wait_time : 3
quality : 65
image_format : jpeg
video_format : mp4
codec : hevc_nvenc
bitrate : 2M
frame_rate : 30
tool_for_images : PIL
tool_for_videos : ffmpeg
delete_source : False
database : database.db
files_table : source_destination
files_metadata_table : metadata