source : /home/puneeth/Pictures/Files/tmp/
destination : /home/puneeth/Pictures/Files/tmp1/
compression_type : 7z
uplink_path_destination : Memories20220919/
uplink_path_type : sj://
log_file : /home/puneeth/Pictures/Files/log.txt
parallel_upload : 1